# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: address_validation.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import client_pb2 as google_dot_api_dot_client__pb2
from google.api import http_pb2 as google_dot_api_dot_http__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x61\x64\x64ress_validation.proto\x1a\x17google/api/client.proto\x1a\x15google/api/http.proto\x1a\x1cgoogle/api/annotations.proto\")\n\x16ValidateAddressRequest\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\"*\n\x17ValidateAddressResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2y\n\x11\x41\x64\x64ressValidation\x12\x64\n\x0fValidateAddress\x12\x17.ValidateAddressRequest\x1a\x18.ValidateAddressResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\"\x13/v1:validateAddress:\x01*BG\n$com.google.maps.addressvalidation.v1B\x1d\x41\x64\x64ressValidationServiceProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'address_validation_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n$com.google.maps.addressvalidation.v1B\035AddressValidationServiceProtoP\001'
  _ADDRESSVALIDATION.methods_by_name['ValidateAddress']._options = None
  _ADDRESSVALIDATION.methods_by_name['ValidateAddress']._serialized_options = b'\202\323\344\223\002\030\"\023/v1:validateAddress:\001*'
  _globals['_VALIDATEADDRESSREQUEST']._serialized_start=106
  _globals['_VALIDATEADDRESSREQUEST']._serialized_end=147
  _globals['_VALIDATEADDRESSRESPONSE']._serialized_start=149
  _globals['_VALIDATEADDRESSRESPONSE']._serialized_end=191
  _globals['_ADDRESSVALIDATION']._serialized_start=193
  _globals['_ADDRESSVALIDATION']._serialized_end=314
# @@protoc_insertion_point(module_scope)
