# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import address_validation_pb2 as address__validation__pb2


class AddressValidationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ValidateAddress = channel.unary_unary(
                '/AddressValidation/ValidateAddress',
                request_serializer=address__validation__pb2.ValidateAddressRequest.SerializeToString,
                response_deserializer=address__validation__pb2.ValidateAddressResponse.FromString,
                )


class AddressValidationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ValidateAddress(self, request, context):
        """Validates an address.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AddressValidationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ValidateAddress': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateAddress,
                    request_deserializer=address__validation__pb2.ValidateAddressRequest.FromString,
                    response_serializer=address__validation__pb2.ValidateAddressResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'AddressValidation', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AddressValidation(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ValidateAddress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AddressValidation/ValidateAddress',
            address__validation__pb2.ValidateAddressRequest.SerializeToString,
            address__validation__pb2.ValidateAddressResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
