# coding: utf-8

"""
    ItemsAPI

    Simple API to get item details

    The version of the OpenAPI document: 0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.items_item_id_get200_response import ItemsItemIdGet200Response  # noqa: E501

class TestItemsItemIdGet200Response(unittest.TestCase):
    """ItemsItemIdGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ItemsItemIdGet200Response:
        """Test ItemsItemIdGet200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ItemsItemIdGet200Response`
        """
        model = ItemsItemIdGet200Response()  # noqa: E501
        if include_optional:
            return ItemsItemIdGet200Response(
                item_id = ''
            )
        else:
            return ItemsItemIdGet200Response(
        )
        """

    def testItemsItemIdGet200Response(self):
        """Test ItemsItemIdGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
