# coding: utf-8

"""
    ItemsAPI

    Simple API to get item details

    The version of the OpenAPI document: 0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi  # noqa: E501


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_items_item_id_get(self) -> None:
        """Test case for items_item_id_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
