# coding: utf-8

# flake8: noqa
"""
    ItemsAPI

    Simple API to get item details

    The version of the OpenAPI document: 0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from openapi_client.models.items_item_id_get200_response import ItemsItemIdGet200Response
